env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8000"
  timeout: 5s
  idle_timeout: 60s
  user: "MOONLAYT"
  password: "1234"

clients:
  sso:
    address: "localhost:44044"
    timeout: 5s
    retries_count: 3
